on:
  - manual
  - pre-push
container:
  arch:
    - x64
    - arm64
steps:
  - name: format
    run: cargo fmt --check

  - name: lint
    run: cargo clippy --target-dir target/$CI_ARCH --all-targets -- -D warnings

  - name: test
    run: cargo test --target-dir target/$CI_ARCH --all

  - name: build
    run: cargo build --target-dir target/$CI_ARCH --release

  - name: install executable
    if: exists(src)
    use: export
    src: target/${{ env.CI_ARCH }}/release/ci
    dest: ~/.local/bin/ci-${{ env.CI_ARCH }}
    replace: true

  - name: generate bash completion
    run: target/$CI_ARCH/release/ci completion bash --output target/$CI_ARCH/generated/completions/ci
  - name: install bash completion
    use: export
    src: target/${{ env.CI_ARCH }}/generated/completions/ci
    dest: ~/.local/share/bash-completion/completions/ci
    replace: true

  - name: generate manual
    run: target/$CI_ARCH/release/ci man --dir target/$CI_ARCH/generated/man/man1
  - name: install manual
    use: export
    src: target/${{ env.CI_ARCH }}/generated/man/man1/*
    dest: ~/.local/share/man/man1/
    replace: true
