on:
  - manual
  - pre-push

steps:
  - name: format
    if: exists(cargo)
    run: cargo fmt --check
  - name: format
    if: missing(cargo) and exists(toolbox)
    run: toolbox run cargo fmt --check

  - name: lint
    if: exists(cargo)
    run: cargo clippy --all-targets -- -D warnings
  - name: 
    if: missing(cargo) and exists(toolbox)
    run: toolbox run cargo clippy --all-targets -- -D warnings

  - name: test
    if: exists(cargo)
    run: cargo test --all
  - name: 
    if: missing(cargo) and exists(toolbox)
    run: toolbox run cargo test --all

  - name: build
    if: exists(cargo)
    run: cargo build --release
  - name: 
    if: missing(cargo) and exists(toolbox)
    run: toolbox run cargo build --release

  - name: install executable
    if: exists(src)
    container: false
    use: export
    src: target/release/ci
    dest: '~/.local/bin/ci.${{ env.CI_ARCH }}'
    replace: true

  - use: link
    if: arch(x64)
    src: '~/.local/bin/ci.${{ env.CI_ARCH }}'
    dest: ~/.local/bin/ci
    replace: true

  - name: install bash completion
    container: false
    run: |
      mkdir -p ~/.local/share/bash-completion/completions
      ci completion bash > ~/.local/share/bash-completion/completions/ci
  - name: install manual
    container: false
    run: |
      mkdir -p ~/.local/share/man/man1
      ci man --dir ~/.local/share/man/man1
