on:
  - manual
  - pre-push
arch:
  - x64
  - arm64
steps:
  - name: format
    if: exists(cargo)
    run: cargo fmt --check
  - name: format
    if: missing(cargo)
    run: toolbox run cargo fmt --check

  - name: lint
    if: exists(cargo)
    run: cargo clippy --all-targets -- -D warnings
  - name: lint
    if: missing(cargo)
    run: toolbox run cargo clippy --all-targets -- -D warnings

  - name: test
    if: exists(cargo)
    run: cargo test --all
  - name: test
    if: missing(cargo)
    run: toolbox run cargo test --all

  - name: build
    if: exists(cargo)
    run: cargo build --release
  - name: build
    if: missing(cargo)
    run: toolbox run cargo build --release

  - name: install executable
    if: exists(src)
    use: export
    src: target/release/ci
    dest: ~/.local/bin/
    replace: true

  - name: install bash completion
    run: ci completion bash > ~/.local/share/bash-completion/completions/ci
  - name: install manual
    run: ci man --dir ~/.local/share/man/man1
